name: apmth115

channels:
- conda-forge

dependencies:
- jupyterlab
- numpy
- pandas
- matplotlib
- seaborn
- scipy
- pip
- python>=3.10
- requests
- scikit-learn
- ipywidgets
- pip:
  - nba_api
  - yfinance
