name: cs1060

channels:
- conda-forge

dependencies:
- jupyterlab
- numpy
- pandas
- matplotlib
- scipy
- pip
- python>=3.10
- requests
- pytorch>=1.8
- pip:
  - torch --index-url https://download.pytorch.org/whl/cu124
  - torchvision --index-url https://download.pytorch.org/whl/cu124
  - torchaudio --index-url https://download.pytorch.org/whl/cu124
  - onnx>=1.12.0
  - onnxslim
  - ultralytics
