name: neuro140

channels:
    - conda-forge

dependencies:
    - arviz==0.17.0
    - beautifulsoup4==4.12.3
    - h5py==3.11.0
    - imageio==2.33.1
    - ipython==8.20.0
    - jupyterlab==4.0.11
    - matplotlib==3.8.2
    - nltk==3.8.1
    - numpy==1.26.3
    - pandas==2.2.0
    - pillow==10.2.0
    - pip==23.3.2
    - plotly==5.18.0
    - python==3.11.7
    - pymc==5.10.3
    - requests==2.31.0
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - seaborn==0.13.1
    - statsmodels==0.14.1
    - tqdm==4.66.1
    - transformers==4.37.0

    - pip:
      - datasets==2.18.0
      - opencv-python-headless==4.9.0.80
      - tensorflow==2.15.0
      - tensorflow_addons==0.23.0
      - tensorflow_datasets==4.9.4
      - tensorflow_hub==0.16.0
      - torch==2.2.1
      - torch_geometric==2.5.2
      - torchvision==0.17.1
      - torchaudio==2.2.1
      - tf_keras_vis==0.8.6 # also adds keras
      - xgboost==2.0.3